### ISSUE TITLE
Make it possible to override image repository/registry in citrix-ingress-controller

### ISSUE THREAD

**Issue by ONordander** [citrix/citrix-helm-charts#132]
Hi.
Currently it's not possible to override only the image repository or registry, it's only possible to override the full image reference.
In a setting where the images are mirrored it would be great if we could just specify a different repository but use the default chart tag like so:
#### **`values.yaml`**
```yaml
image:
  registry: quay.io
  repository: citrix/citrix-k8s-ingress-controller
  tag: 1.26.7 
```
And then we could override it:

#### **`override-values.yaml`**
```yaml
image:
  registry: myregistry.com
  repository: mirrors/citrix/citrix-k8s-ingress-controller
```

See an example here https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
