### ISSUE TITLE
Citrix-ingress-control fails helm 3 validation

### ISSUE THREAD

**Issue by BenB196** [citrix/citrix-helm-charts#29]
Attempt to install citrix-ingress-controll via helm 3.

Get the error: 
```
Wait helm template failed. Error: apiVersion 'v2' is not valid. The value must be "v1" : exit status 1
```

This implies that even though the [Chart.yaml](https://github.com/citrix/citrix-helm-charts/blob/master/citrix-ingress-controller/Chart.yaml) is set to use helm 3, there is something within this deployment that does not properly validate against helm 3.

Attempting to use on Kubernetes v1.18.6

**Comment by priyankash-citrix** [comment]
@BenB196 I have deployed citrix-ingress-controller chart with Helm 3.x in Kubernetes v1.17.3, v1.18.0 and v1.19.0 and it is working as expected in these 3 version.
Can you please specify exact helm version which you are using? I will bring up Kubernetes cluster with version v1.18.6 and will try to reproduce this issue.

**Comment by BenB196** [comment]
I'm using Rancher (v2.4.8) with Helm v3 (v3.2.0)

**Comment by BenB196** [comment]
@priyankash-citrix I removed and readded and am no longer getting:
```
Wait helm template failed. Error: apiVersion 'v2' is not valid. The value must be "v1" : exit status 1
```

However, I am now getting:

```
Wait helm template failed. Error: YAML parse error on citrix-ingress-controller/templates/cic_crds.yaml: error converting YAML to JSON: yaml: line 4: did not find expected key
```

Here are the values I'm passing:

```
---
  crds:
    install: "true"
    retainOnDelete: "false"
  http2ServerSide: "ON"
  exporter:
    required: "true"
  ingressClass:
    - citrix
  license:
    accept: "yes"
  logLevel: "DEBUG"
  loginFileName: "nslogin"
  nodeWatch: true
  nsIP: "<snipped_ip>"
  nsPort: "443"
  nsProtocol: "HTTPS"
  nsVIP: "<snipped_ip>"
  openshift: false
```
